def name = "app"
def namespace = "my-team-1001"
def imageName = "localhost:32000/app"
def imageTag = "1.4.1" // image's tag
def podReplicaCount = "3"
def serviceType = "NodePort" // None, NodePort, ClusterIP, LoadBalancer
def port = "3000"
def nodePort = "32003" // if serviceType is NodePort
def targetPort = "3000"

podTemplate(cloud: 'kubernetes', containers: [
    containerTemplate(
        name: 'kubectl',
        image: 'localhost:32000/kubectl:1.1',
        ttyEnabled: true,
        privileged: false,
        alwaysPullImage: false,
        workingDir: '/home/jenkins/agent',
        resourceRequestCpu: '50m',
        resourceLimitCpu: '100m',
        resourceRequestMemory: '100Mi',
        resourceLimitMemory: '200Mi',
        command: 'cat'
    )
],
volumes: [
    configMapVolume(mountPath: '/home/jenkins/agent/.kube', configMapName: 'jenkins-cluster-master')
]
) {
  node(POD_LABEL)  {
    stage('Run maven') {
      container('kubectl') {
        checkout scm
        sh """
          helm template \
            --set project.name=${name} \
            --set project.namespace=${namespace} \
            --set project.pod.image.name=${imageName} \
            --set project.pod.image.tag=${imageTag} \
            --set project.pod.replicas=${podReplicaCount} \
            --set project.service.type=${serviceType} \
            --set project.service.port=${port} \
            --set project.service.targetPort=${targetPort} \
            --set project.service.nodePort=${nodePort} \
            healthy/chart/ \
          | kubectl apply -f - 
        """
      }
    }
  }
}
