apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.project.name }}
  namespace: {{ .Values.project.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.project.gateway.name }}
  http:
    - route:
      - destination:
          host: {{ .Values.project.name }}.{{ .Values.project.namespace }}.svc.cluster.local
          subset: blue
        weight: 100
      - destination:
          host: {{ .Values.project.name }}.{{ .Values.project.namespace }}.svc.cluster.local
          subset: green
        weight: 0
