apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.project.name }}
spec:
  host: {{ .Values.project.name }}
  subsets:
  - name: blue
    labels:
      version: {{ .Values.project.version.blue }}
  - name: green
    labels:
      version: {{ .Values.project.version.green }}
